/*
 * Copyright 2015 Facundo Lopez Kaufmann.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.mule.tooling.netbeans.ui.runtime.view;

import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import org.mule.tooling.netbeans.api.MuleSupport;
import org.openide.util.NbBundle.Messages;
import org.mule.tooling.netbeans.api.MuleRuntime;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;

/**
 *
 * @author Facundo Lopez Kaufmann
 */
@Messages({
    "MuleLicenseView_Title=Select License",
    "MuleLicenseView_UpdateLicenseActionTitle=Add License...",
})
public class MuleLicenseView extends javax.swing.JPanel {

    public static Path capture() {
        final MuleLicenseView view = new MuleLicenseView();
        view.getAccessibleContext().setAccessibleDescription(Bundle.MuleLicenseView_Title());
        DialogDescriptor dd = new DialogDescriptor(view, Bundle.MuleLicenseView_UpdateLicenseActionTitle());
        dd.setClosingOptions(new Object[] {
            view.getOKButton(),
            DialogDescriptor.CANCEL_OPTION
        });
        dd.setOptions(new Object[]{
            view.getOKButton(),
            DialogDescriptor.CANCEL_OPTION
        });
        if (view.getOKButton() == DialogDisplayer.getDefault().notify(dd)) {
            return view.getMuleHome();
        } else {
            return null;
        }
    }

    /**
     * Creates new form ConfigurationView
     */
    private MuleLicenseView() {
        initComponents();
        validateInformation();
    }

    private MuleRuntime getMuleRuntime() {
        return MuleSupport.getMuleRuntime(getMuleHome());
    }

    public Path getMuleHome() {
        return Paths.get(txtLicensePath.getText());
    }

    @Messages({
        "MuleLicenseView_validation_LicensePathNotEmpty=License path can't be empty",
    })
    private void validateInformation() {
        //check mule home
        if (txtLicensePath.getText().trim().length() == 0) {
            lblValidate.setText(Bundle.MuleLicenseView_validation_LicensePathNotEmpty());
            btnOk.setEnabled(false);
            return;
        }
        lblValidate.setText("");
        btnOk.setEnabled(true);
    }

    public javax.swing.JButton getOKButton() {
        return btnOk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        txtLicensePath = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        lblLicensePath = new javax.swing.JLabel();
        lblValidate = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(btnOk, org.openide.util.NbBundle.getMessage(MuleLicenseView.class, "MuleLicenseView.btnOk.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblHeader, org.openide.util.NbBundle.getMessage(MuleLicenseView.class, "MuleLicenseView.lblHeader.text")); // NOI18N

        txtLicensePath.setText(org.openide.util.NbBundle.getMessage(MuleLicenseView.class, "MuleLicenseView.txtLicensePath.text")); // NOI18N
        txtLicensePath.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(btnBrowse, org.openide.util.NbBundle.getMessage(MuleLicenseView.class, "MuleLicenseView.btnBrowse.text")); // NOI18N
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblLicensePath, org.openide.util.NbBundle.getMessage(MuleLicenseView.class, "MuleLicenseView.lblLicensePath.text")); // NOI18N

        lblValidate.setForeground(new java.awt.Color(204, 0, 0));
        org.openide.awt.Mnemonics.setLocalizedText(lblValidate, org.openide.util.NbBundle.getMessage(MuleLicenseView.class, "MuleLicenseView.lblValidate.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValidate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLicensePath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLicensePath, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowse)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLicensePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse)
                    .addComponent(lblLicensePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValidate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setSelectedFile(new File(txtLicensePath.getText().trim()));
        if (chooser.showOpenDialog(SwingUtilities.getWindowAncestor(this)) == JFileChooser.APPROVE_OPTION) {
            txtLicensePath.setText(chooser.getSelectedFile().getAbsolutePath());
            validateInformation();
        }
    }//GEN-LAST:event_btnBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLicensePath;
    private javax.swing.JLabel lblValidate;
    private javax.swing.JTextField txtLicensePath;
    // End of variables declaration//GEN-END:variables
}
